// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5SOYwzyqyjMAPm12Qw3HLDfbL4VLDShM',
    appId: '1:698472966152:web:10d4b05b3f68e38e6b49bd',
    messagingSenderId: '698472966152',
    projectId: 'ticketbox-57476',
    authDomain: 'ticketbox-57476.firebaseapp.com',
    storageBucket: 'ticketbox-57476.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjyXEDUiRJpfLfn7qgHitB1NEf8kEUiA',
    appId: '1:698472966152:android:63099b88248a67e36b49bd',
    messagingSenderId: '698472966152',
    projectId: 'ticketbox-57476',
    storageBucket: 'ticketbox-57476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3fSqXiqbPwvn1FZdrAEDPnswCblhraJI',
    appId: '1:698472966152:ios:37921d268642ce846b49bd',
    messagingSenderId: '698472966152',
    projectId: 'ticketbox-57476',
    storageBucket: 'ticketbox-57476.firebasestorage.app',
    iosBundleId: 'com.example.ticketbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3fSqXiqbPwvn1FZdrAEDPnswCblhraJI',
    appId: '1:698472966152:ios:37921d268642ce846b49bd',
    messagingSenderId: '698472966152',
    projectId: 'ticketbox-57476',
    storageBucket: 'ticketbox-57476.firebasestorage.app',
    iosBundleId: 'com.example.ticketbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5SOYwzyqyjMAPm12Qw3HLDfbL4VLDShM',
    appId: '1:698472966152:web:d5e59a9167526bde6b49bd',
    messagingSenderId: '698472966152',
    projectId: 'ticketbox-57476',
    authDomain: 'ticketbox-57476.firebaseapp.com',
    storageBucket: 'ticketbox-57476.firebasestorage.app',
  );
}
